### ISSUE TITLE
Are the changes made here immediately applied to the documentation site?

### ISSUE THREAD

**Issue by scottpedia** [iredmail/docs#18]
Hi

I pulled this repo and wanted to contribute by translating the documents. But the name of some documents in this repo do not match the corresponding articles on the documentation site. For example, `Allow user to send email without smtp authentication.md` does not match [Allow some user to send email without smtp authentication](https://docs.iredmail.org/allow.send.without.smtp.auth.html).

**Comment by Scottpedia** [comment]
sorry my fault... closing.
