### ISSUE TITLE
Does SPF Replace PTR?

### ISSUE THREAD

**Issue by johnaweiss** [iredmail/docs#2]
Re your document, 

https://docs.iredmail.org/setup.dns.html

I was told by a Microsoft engineer that PTR is deprecated, and SPF serves the same purpose. Is that correct?

thx

**Comment by iredmail** [comment]
Completely wrong.

PTR and SPF are different:

- PTR is IP to hostname mapping.
- SPF is "Sender Policy Framework", it queries DNS record to get a list of IP addresses/networks which are allowed to send email as your mail domain.

**Comment by johnaweiss** [comment]
These sites state: 

> This mechanism is deprecated and should no longer be used for performance issue.
> https://www.bettercloud.com/monitor/spf-dkim-dmarc-email-security/
> https://www.emailarchitect.net/domainkeys/doc/html/object_spf.htm

True?

**Comment by iredmail** [comment]
Still many mail servers check PTR record. It's better to add PTR record for your server IP address if possible.
