### ISSUE TITLE
Add potentially useful website that checks how likely your email is to be received to installation docs.

### ISSUE THREAD

**Issue by Dante-De-Gruyter** [iredmail/docs#42]
I have a proposal, 
[this website](https://www.mail-tester.com/) gives you a lot of useful information about the emails sent by your iRedMail installation, and in my case helped me diagnose some DNS record problems.
Would it be a good idea to add a link to this website to some installation docs?

**Comment by iredmail** [comment]
Is it better developing (by iRedMail team) an online tool to help diagnose DNS records like mail-tester.com? also setup DNS records.

**Comment by iredmail** [comment]
Working on it.
